version: '3.3'
services:
  mysqldb:
    image: mysql:latest
    networks:
      - ecommerce
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8088:8088
    networks:
      - ecommerce
    environment:
      - spring.datasource.url=jdbc:mariadb://mysqldb:3306/ecommerce?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

volumes:
  my-db:
networks:
  ecommerce: