name: ecommerce-dev-container
services:
  ec-test-mariadb:
    container_name: ec-test-mariadb
    image: mariadb:10.8
    networks:
      - ec-test-ecommerce
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: ecommerce
    labels:
      org.springframework.boot.ignore: true
  
  ec-test-cache:
    container_name: ec-test-cache
    image: 'bitnami/redis:latest'
    networks:
      - ec-test-ecommerce
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  ec-test-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - ec-test-ecommerce
    container_name: ec-test-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  ec-test-broker:
    image: confluentinc/cp-kafka:7.0.1
    networks:
      - ec-test-ecommerce
    container_name: ec-test-broker
    ports:
      - "9092:9092"
    depends_on:
      - ec-test-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'ec-test-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
volumes:
  ec-test-mysql:
networks:
  ec-test-ecommerce: